# Generated by Django 5.1.2 on 2024-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SlotModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pduct_id", models.BigIntegerField()),
                ("no", models.IntegerField()),
                ("is_booked", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Slot",
                "verbose_name_plural": "Slots",
                "db_table": "slot",
                "abstract": False,
            },
        ),
    ]
